### ISSUE TITLE
Crash in Raccoon bundle menu

### ISSUE THREAD

**Issue by Shadowcat42** [stardew-access/stardew-access#323]
The raccoon's third request, at least on my end entirely breaks the bundle menu in such a way that I can't fix whatsoever, other than restarting the game. To be more specific, here's what happens. I press I to cycle through the required items. The first is dried mushrooms, which although says error item works fine. The second time I press I, however, the menu no longer responds at all, and the only thing I can do is close it. Reopening the menu does nothing. Here's what I found in the error log.
[20:29:09 ERROR Stardew Access] An error occurred in Junimo Note Menu patch:
Value cannot be null. (Parameter 'key')
   at System.Collections.Generic.Dictionary`2.FindValue(TKey key)
   at System.Collections.Generic.Dictionary`2.TryGetValue(TKey key, TValue& value)
   at StardewValley.Object..ctor(String itemId, Int32 initialStack, Boolean isRecipe, Int32 price, Int32 quality) in D:\GitlabRunner\builds\Gq5qA5P4\0\ConcernedApe\stardewvalley\Farmer\Farmer\Objects\Object.cs:line 589
   at stardew_access.Patches.JunimoNoteMenuPatch.CycleThroughIngredientList(JunimoNoteMenu __instance, Bundle ___currentPageBundle, Boolean isLeftShiftPressed) in C:\Users\katalina\code\stardew-access\stardew-access\Patches\BundleMenuPatches\JunimoNoteMenuPatch.cs:line 210
   at stardew_access.Patches.JunimoNoteMenuPatch.NarrateBundlePage(JunimoNoteMenu __instance, Boolean ___specificBundlePage, Bundle ___currentPageBundle, Int32 x, Int32 y) in C:\Users\katalina\code\stardew-access\stardew-access\Patches\BundleMenuPatches\JunimoNoteMenuPatch.cs:line 147
   at stardew_access.Patches.JunimoNoteMenuPatch.DrawPatch(JunimoNoteMenu __instance, Boolean ___specificBundlePage, Int32 ___whichArea, Bundle ___currentPageBundle) in C:\Users\katalina\code\stardew-access\stardew-access\Patches\BundleMenuPatches\JunimoNoteMenuPatch.cs:line 44

**Comment by LucieG0** [comment]
Also there are some items that are read as error items like the jelly, the dried fruits etc.

**Comment by khanshoaib3** [comment]
@Shadowcat42 Can you confirm this issue with the new beta.

**Comment by Shadowcat42** [comment]
Yup, seems to be fixed on my end. Thank you!
