### ISSUE TITLE
New install error on load

### ISSUE THREAD

**Issue by nadriatucker** [stardew-access/stardew-access#355]
I got Stardew Access installed on Mac and the game opens but immediately  starts throwing up this "“libspeak.dylib” can’t be opened because Apple cannot check it for malicious software" error over and over. Anybody have a fix

Here's what the terminal says:
[Stardew Access] This mod failed in the Display.Rendering event. Technical details: 
Failed loading type '': DllNotFoundException: Unable to load shared library 'lib/screen-reader-libs/macos/libspeak.dylib' or one of its dependencies. In order to help diagnose loading problems, consider setting the DYLD_PRINT_LIBRARIES environment variable: dlopen(lib/screen-reader-libs/macos/libspeak.dylib, 0x0001): tried: 'lib/screen-reader-libs/macos/libspeak.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OSlib/screen-reader-libs/macos/libspeak.dylib' (no such file), '/usr/lib/lib/screen-reader-libs/macos/libspeak.dylib' (no such file, not in dyld cache), 'lib/screen-reader-libs/macos/libspeak.dylib' (no such file)
   at CrossSpeak.ScreenReaderMac.LibSpeakAPI.make_speaker()
   at CrossSpeak.ScreenReaderMac.Initialize()
   at stardew_access.ScreenReader.ScreenReaderImpl.InitializeScreenReader() in /home/towk/Projects/stardew-access/stardew-access/ScreenReader/ScreenReaderImpl.cs:line 57
   at stardew_access.MainClass.get_ScreenReader() in /home/towk/Projects/stardew-access/stardew-access/ModEntry.cs:line 41
   at stardew_access.MainClass.OnRenderingStart(Object sender, RenderingEventArgs renderingEventArgs) in /home/towk/Projects/stardew-access/stardew-access/ModEntry.cs:line 184
   at StardewModdingAPI.Framework.Events.ManagedEvent`1.Raise(TEventArgs args) in SMAPI\Framework\Events\ManagedEvent.cs:line 101
[Stardew Access] Could not load favorites.json or the file is empty.
[SMAPI] Critical app domain exception: System.DllNotFoundException: Unable to load shared library 'lib/screen-reader-libs/macos/libspeak.dylib' or one of its dependencies. In order to help diagnose loading problems, consider setting the DYLD_PRINT_LIBRARIES environment variable: dlopen(lib/screen-reader-libs/macos/libspeak.dylib, 0x0001): tried: 'lib/screen-reader-libs/macos/libspeak.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OSlib/screen-reader-libs/macos/libspeak.dylib' (no such file), '/usr/lib/lib/screen-reader-libs/macos/libspeak.dylib' (no such file, not in dyld cache), 'lib/screen-reader-libs/macos/libspeak.dylib' (no such file)
   at CrossSpeak.ScreenReaderMac.LibSpeakAPI.cleanup_with(IntPtr speaker)
   at CrossSpeak.ScreenReaderMac.Close()
   at System.AppContext.OnProcessExit()

**Comment by LucieG0** [comment]
Hi, when you launch do you get the pop up about not opening libspeak because it's out of date and needing to contact the developer? Because I believe I got round that error by going to system preferences and enabling it under the security section like you would with other files it considers unsafe to open.

**Comment by ParadoxiKat** [comment]
Bumping this issue -- @nadriatucker were you able to resolve this issue with @LucieG0's suggestion?
Either way, @PepperTheVixen we should make sure what @LucieG0 is suggesting is listed in the mac install guides.
